config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :groups

  devise_for :users
  root to: 'dashboard#index'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/admin'

  get 'checks/new'
  post 'checks/create' => 'checks#create'
  get 'checks/:id' => 'checks#show'
  post 'checks/update' => 'checks#update'

  get 'terminals/feature'
  get 'terminals/ios'
  get 'terminals/android'
  resources :terminals

  resources :terminal_masters

  resources :screen_densities

  resources :makers

  resources :carriers

end

app/models/terminal_master.rb
class TerminalMaster < ActiveRecord::Base
  belongs_to :carrier
  belongs_to :maker
  belongs_to :group
  belongs_to :screen_density
end

app/controllers/terminal_masters_controller.rb
class TerminalMastersController < ApplicationController
  before_action :set_terminal_master, only: [:show, :edit, :update, :destroy]
  authorize_actions_for User

  # GET /terminal_masters
  # GET /terminal_masters.json
  def index
    @terminal_masters = TerminalMaster.all
  end

  # GET /terminal_masters/1
  # GET /terminal_masters/1.json
  def show
  end

  # GET /terminal_masters/new
  def new
    @terminal_master = TerminalMaster.new
  end

  # GET /terminal_masters/1/edit
  def edit
  end

  # POST /terminal_masters
  # POST /terminal_masters.json
  def create
    @terminal_master = TerminalMaster.new(terminal_master_params)

    respond_to do |format|
      if @terminal_master.save
        format.html { redirect_to @terminal_master, notice: t('view.create_message', target: t('activerecord.attributes.models.terminal_master')) }
        format.json { render action: 'show', status: :created, location: @terminal_master }
      else
        format.html { render action: 'new' }
        format.json { render json: @terminal_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terminal_masters/1
  # PATCH/PUT /terminal_masters/1.json
  def update
    respond_to do |format|
      if @terminal_master.update(terminal_master_params)
        format.html { redirect_to @terminal_master, notice: t('view.update_message', target: t('activerecord.attributes.models.terminal_master')) }
        format.json { render action: 'show', status: :ok, location: @terminal_master }
      else
        format.html { render action: 'edit' }
        format.json { render json: @terminal_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terminal_masters/1
  # DELETE /terminal_masters/1.json
  def destroy
    @terminal_master.destroy
    respond_to do |format|
      format.html { redirect_to terminal_masters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_terminal_master
      @terminal_master = TerminalMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def terminal_master_params
      params.require(:terminal_master).permit(:carrier_id, :maker_id, :series_id, :model_name, :default_os, :screen_inch_id, :screen_width_id, :screen_height_id, :screen_density_id, :release_date, :tablet, :nfc)
    end
end

app/helpers/terminal_masters_helper.rb
module TerminalMastersHelper
end

app/views/terminal_masters/_form.html.haml
= simple_form_for @terminal_master, :html => { :class => 'form-horizontal' } do |f|
  .form-group.string.optional.terminal_master
    = f.label :carrier_id, class: 'col-sm-2 control-label'
    .form-group
      .col-sm-6
        = f.collection_select :carrier_id, Terminal.all, :id, :name, {}, {class: 'form-control'}
  .form-group.string.optional.terminal_master
    = f.label :maker_id, class: 'col-sm-2 control-label'
    .form-group
      .col-sm-6
        = f.collection_select :maker_id, Maker.all, :id, :name, {}, {class: 'form-control'}
  .form-group.string.optional.terminal_master
    = f.label :group_id, class: 'col-sm-2 control-label'
    .form-group
      .col-sm-6
        = f.collection_select :group_id, Group.all, :id, :name, {}, {class: 'form-control'}
  = f.input :model_name
  = f.input :default_os
  = f.input :screen_inch
  = f.input :screen_width
  = f.input :screen_height
  .form-group.string.optional.terminal_master
    = f.label :screen_density_id, class: 'col-sm-2 control-label'
    .form-group
      .col-sm-6
        = f.collection_select :screen_density_id, ScreenDensity.all, :id, :size, {}, {class: 'form-control'}
  = f.input :release_date
  = f.input :tablet
  = f.input :nfc
  = f.button :submit, class: 'btn-primary col-sm-offset-2'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), terminal_masters_path, :class => 'btn btn-default'

app/views/terminal_masters/edit.html.haml
- model_class = TerminalMaster
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/terminal_masters/index.html.haml
- model_class = TerminalMaster
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:carrier_id)
      %th= model_class.human_attribute_name(:maker_id)
      %th= model_class.human_attribute_name(:group_id)
      %th= model_class.human_attribute_name(:model_name)
      %th= model_class.human_attribute_name(:default_os)
      %th= model_class.human_attribute_name(:screen_inch)
      %th= model_class.human_attribute_name(:screen_width)
      %th= model_class.human_attribute_name(:screen_height)
      %th= model_class.human_attribute_name(:screen_density_id)
      %th= model_class.human_attribute_name(:release_date)
      %th= model_class.human_attribute_name(:tablet)
      %th= model_class.human_attribute_name(:nfc)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @terminal_masters.each do |terminal_master|
      %tr
        %td= link_to terminal_master.id, terminal_master_path(terminal_master)
        %td= terminal_master.carrier.name
        %td= terminal_master.maker.name
        %td= terminal_master.group.name
        %td= terminal_master.model_name
        %td= terminal_master.default_os
        %td= terminal_master.screen_inch
        %td= terminal_master.screen_width
        %td= terminal_master.screen_height
        %td= terminal_master.screen_density.size
        %td= format_date(terminal_master.release_date)
        %td= terminal_master.tablet
        %td= terminal_master.nfc
        %td=l terminal_master.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_terminal_master_path(terminal_master), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), terminal_master_path(terminal_master), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_terminal_master_path, :class => 'btn btn-primary'

app/views/terminal_masters/new.html.haml
- model_class = TerminalMaster
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/terminal_masters/show.html.haml
- model_class = TerminalMaster
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:carrier_id) + ':'
  %br
  = @terminal_master.carrier_id
%p
  %strong= model_class.human_attribute_name(:maker_id) + ':'
  %br
  = @terminal_master.maker_id
%p
  %strong= model_class.human_attribute_name(:group_id) + ':'
  %br
  = @terminal_master.group_id
%p
  %strong= model_class.human_attribute_name(:model_name) + ':'
  %br
  = @terminal_master.model_name
%p
  %strong= model_class.human_attribute_name(:default_os) + ':'
  %br
  = @terminal_master.default_os
%p
  %strong= model_class.human_attribute_name(:screen_inch) + ':'
  %br
  = @terminal_master.screen_inch
%p
  %strong= model_class.human_attribute_name(:screen_width) + ':'
  %br
  = @terminal_master.screen_width
%p
  %strong= model_class.human_attribute_name(:screen_height) + ':'
  %br
  = @terminal_master.screen_height
%p
  %strong= model_class.human_attribute_name(:screen_density_id) + ':'
  %br
  = @terminal_master.screen_density_id
%p
  %strong= model_class.human_attribute_name(:release_date) + ':'
  %br
  = @terminal_master.release_date
%p
  %strong= model_class.human_attribute_name(:tablet) + ':'
  %br
  = @terminal_master.tablet
%p
  %strong= model_class.human_attribute_name(:nfc) + ':'
  %br
  = @terminal_master.nfc


= link_to t('.back', :default => t("helpers.links.back")), terminal_masters_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_terminal_master_path(@terminal_master), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), terminal_master_path(@terminal_master), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'