config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :groups

  devise_for :users
  root to: 'dashboard#index'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/admin'

  get 'checks/new'
  post 'checks/create' => 'checks#create'
  get 'checks/:id' => 'checks#show'
  post 'checks/update' => 'checks#update'

  get 'terminals/feature'
  get 'terminals/ios'
  get 'terminals/android'
  resources :terminals

  resources :terminal_masters

  resources :screen_densities

  resources :makers

  resources :carriers

end

app/models/screen_density.rb
class ScreenDensity < ActiveRecord::Base
end

app/controllers/screen_densities_controller.rb
class ScreenDensitiesController < ApplicationController
  before_action :set_screen_density, only: [:show, :edit, :update, :destroy]
  authorize_actions_for User

  # GET /screen_densities
  # GET /screen_densities.json
  def index
    @screen_densities = ScreenDensity.all
  end

  # GET /screen_densities/1
  # GET /screen_densities/1.json
  def show
  end

  # GET /screen_densities/new
  def new
    @screen_density = ScreenDensity.new
  end

  # GET /screen_densities/1/edit
  def edit
  end

  # POST /screen_densities
  # POST /screen_densities.json
  def create
    @screen_density = ScreenDensity.new(screen_density_params)

    respond_to do |format|
      if @screen_density.save
        format.html { redirect_to @screen_density, notice: t('view.create_message', target: t('activerecord.attributes.models.screen_density')) }
        format.json { render action: 'show', status: :created, location: @screen_density }
      else
        format.html { render action: 'new' }
        format.json { render json: @screen_density.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screen_densities/1
  # PATCH/PUT /screen_densities/1.json
  def update
    respond_to do |format|
      if @screen_density.update(screen_density_params)
        format.html { redirect_to @screen_density, notice: t('view.update_message', target: t('activerecord.attributes.models.screen_density')) }
        format.json { render action: 'show', status: :ok, location: @screen_density }
      else
        format.html { render action: 'edit' }
        format.json { render json: @screen_density.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screen_densities/1
  # DELETE /screen_densities/1.json
  def destroy
    @screen_density.destroy
    respond_to do |format|
      format.html { redirect_to screen_densities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screen_density
      @screen_density = ScreenDensity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screen_density_params
      params.require(:screen_density).permit(:size)
    end
end

app/helpers/screen_densities_helper.rb
module ScreenDensitiesHelper
end

app/views/screen_densities/_form.html.haml
= simple_form_for @screen_density, :html => { :class => 'form-horizontal' } do |f|
  = f.input :size
  = f.button :submit, class: 'btn-primary col-sm-offset-2'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), screen_densities_path, :class => 'btn btn-default'

app/views/screen_densities/edit.html.haml
- model_class = ScreenDensity
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/screen_densities/index.html.haml
- model_class = ScreenDensity
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:size)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @screen_densities.each do |screen_density|
      %tr
        %td= link_to screen_density.id, screen_density_path(screen_density)
        %td= screen_density.size
        %td=l screen_density.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_screen_density_path(screen_density), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), screen_density_path(screen_density), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_screen_density_path, :class => 'btn btn-primary'

app/views/screen_densities/new.html.haml
- model_class = ScreenDensity
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/screen_densities/show.html.haml
- model_class = ScreenDensity
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:size) + ':'
  %br
  = @screen_density.size


= link_to t('.back', :default => t("helpers.links.back")), screen_densities_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_screen_density_path(@screen_density), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), screen_density_path(@screen_density), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'