config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :groups

  devise_for :users
  root to: 'dashboard#index'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/admin'

  get 'checks/new'
  post 'checks/create' => 'checks#create'
  get 'checks/:id' => 'checks#show'
  post 'checks/update' => 'checks#update'

  get 'terminals/feature'
  get 'terminals/ios'
  get 'terminals/android'
  resources :terminals

  resources :terminal_masters

  resources :screen_densities

  resources :makers

  resources :carriers

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  authorize_actions_for User

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: t('view.create_message', target: t('activerecord.attributes.models.group')) }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: t('view.update_message', target: t('activerecord.attributes.models.group')) }
        format.json { render action: 'show', status: :ok, location: @group }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :name_kana)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for @group, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :name_kana
  = f.button :submit, class: 'btn-primary col-sm-offset-2'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), groups_path, :class => 'btn btn-default'

app/views/groups/edit.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/groups/index.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:name_kana)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @groups.each do |group|
      %tr
        %td= link_to group.id, group_path(group)
        %td= group.name
        %td= group.name_kana
        %td=l group.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(group), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(group), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_group_path, :class => 'btn btn-primary'

app/views/groups/new.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/groups/show.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @group.name
%p
  %strong= model_class.human_attribute_name(:name_kana) + ':'
  %br
  = @group.name_kana


= link_to t('.back', :default => t("helpers.links.back")), groups_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(@group), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(@group), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'