config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :groups

  devise_for :users
  root to: 'dashboard#index'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/admin'

  get 'checks/new'
  post 'checks/create' => 'checks#create'
  get 'checks/:id' => 'checks#show'
  post 'checks/update' => 'checks#update'

  get 'terminals/feature'
  get 'terminals/ios'
  get 'terminals/android'
  resources :terminals

  resources :terminal_masters

  resources :screen_densities

  resources :makers

  resources :carriers

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: t('view.create_message', target: t('activerecord.attributes.models.category')) }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: t('view.update_message', target: t('activerecord.attributes.models.category')) }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.button :submit, class: 'btn-primary col-sm-offset-2'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default'

app/views/categories/edit.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/index.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.id, category_path(category)
        %td= category.name
        %td=l category.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(category), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary'

app/views/categories/new.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/show.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @category.name


= link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(@category), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(@category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'